---
    
- name: "[{{ name }}] Выкладка сервиса" # снова выкладываем сервис с необходимыми параметрами
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:{{ latest }}"
        state: present
        networks:
          - name: "{{ network_Name }}"
        env:
          - RABBITMQ_DEFAULT_USER={{ rmq.user }}
          - RABBITMQ_DEFAULT_PASS={{ rmq.password }}
  tags: "{{ name }}"