---
- name: Циклы
  debug:
    msg: "{{ item }}"
  loop: 
    - name: Вася
      group: admin
        roles:
          admin: true
          manager: true
          user: true
  loop_control:
    label: "{{ item.name }}"