---
- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3

- name: Создание сети
  community.docker.docker_network:
    name: "{{ networkName }}"
    driver: overlay

- name: Выкладка сервисов
  include_tasks: "../services/{{ item }}/service.yml"
  vars:
    - name: "{{ item }}"
  loop: "{{ services }}"