---
- name: Install bottle for Python 3.3 specifically, using the 'pip3.3' executable
  ansible.builtin.pip:
    name: bottle
    executable: pip3.3

- name: Создание сети
  community.docker.docker_network:
    name: "{{ networkName }}"
    driver: overlay

- name: Выкладка сервисов
  include_tasks: "../services/{{ item }}/service.yml"
  vars:
    - name: "{{ item }}"
  loop: "{{ services }}"