# настройка сервера: установка docker и docker-compose; добавление прав пользователя и перезагрузка сервера
---
- name: all  configs
  hosts: all
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      test: 0
      tags: deploy