---
- name: "[{{ name }}] Конфигурация конфига" # Обрабатываем ситуацию, когда возникает ошибка с помощью блока rsq
  block:
    - name: "[{{ name }}] Создаём конфиг"
      include_tasks: "config-create.yml"
  tags: "{{ name }}"

  rescue:
    - name: "[{{ name }}] Удаляем конфиг" # удаляем сервис
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: present

    - name: "[{{ name }}] Создаём конфиг" # накатываем секрет
      include_tasks: "config-create.yml"