---
- name: "[{{ name }}] Конфигурация секрета" # Обрабатываем ситуацию, когда возникает ошибка с помощью блока rsq
  block:
    - name: "[{{ name }}] Создаём секрет"
      include_tasks: "secret-create.yml"

  rescue:
    - name: "[{{ name }}] Удаляем сервис" # удаляем сервис
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: present

    - name: "[{{ name }}] Создаём секрет" # накатываем секрет
      include_tasks: "secret-create.yml"